# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('logo.png', '.')],
    hiddenimports=[
        'watchdog',
        'watchdog.observers',
        'watchdog.events',
        'watcher',
        'watcher.config',
        'watcher.local_watcher',
        'watcher.network_poller',
        'watcher.manager',
        'watcher.reconciler',
        'ai',
        'ai.client',
        'ai.classifier',
        'ai.parser',
        'ai.prompts',
        'ui',
        'ui.main_window',
        'ui.media_wizard',
        'ui.index_browser_dialog',
        'ui.file_browser',
        'ui.tray_icon',
        'ui.scan_dialog',
        'ui.log_dialog',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='FileRecorder',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['logo.ico'],
)
